apiVersion: apps/v1
kind: Deployment
metadata:
 name: n8n
 namespace: n8n
spec:
 progressDeadlineSeconds: 600
 replicas: 1
 selector:
   matchLabels:
     app.kubernetes.io/name: n8n
 strategy:
   rollingUpdate:
     maxSurge: 25%
     maxUnavailable: 25%
   type: RollingUpdate
 template:
   metadata:
     labels:
       app.kubernetes.io/name: n8n
   spec:
     containers:
     - env:
       - name: GENERIC_TIMEZONE
         value: America/Denver
       - name: N8N_DIAGNOSTICS_ENABLED
         value: "false"
       - name: N8N_VERSION_NOTIFICATIONS_ENABLED
         value: "false"
       - name: N8N_TEMPLATES_ENABLED
         value: "false"
       - name: N8N_LOG_LEVEL
         value: debug
       - name: N8N_LOG_OUTPUT
         value: console
       - name: N8N_EDITOR_BASE_URL
         value: https://n8n.ps.ringcentral.com
       - name: N8N_PORT
         value: "3000"
       - name: N8N_HOST
         value: n8n.ps.ringcentral.com
       - name: N8N_PROTOCOL
         value: http
       - name: EXECUTIONS_PROCESS
         value: main
       - name: N8N_EMAIL_MODE
         value: smtp
       - name: N8N_SMTP_HOST
         value: email-smtp.us-east-1.amazonaws.com
       - name: N8N_SMTP_PORT
         value: "465"
       - name: N8N_SMTP_USER
         value: AKIATXLTLLG5KI3IDDSO
       - name: N8N_SMTP_PASS
         valueFrom:
           secretKeyRef:
             key: smtp-pass
             name: smtp-secrets
       - name: N8N_SMTP_SENDER
         value: n8n@ps.ringcentral.com
       - name: DB_TYPE
         value: postgresdb
       - name: DB_POSTGRESDB_HOST
         value: eks-pgsql-01-cluster.cluster-cpdz7dn54dr4.us-east-2.rds.amazonaws.com
       - name: DB_POSTGRESDB_USER
         value: rcpsadmin
       - name: DB_POSTGRESDB_DATABASE
         value: n8n
       - name: DB_POSTGRESDB_PORT
         value: "5432"
       - name: DB_POSTGRESDB_PASSWORD
         valueFrom:
           secretKeyRef:
             key: db-pass
             name: db-secrets
       - name: N8N_ENCRYPTION_KEY
         valueFrom:
           secretKeyRef:
             key: encryptionKey
             name: n8n
       image: n8nio/n8n:1.89.1
       imagePullPolicy: Always
       name: n8n
       ports:
       - containerPort: 3000
         name: web
         protocol: TCP
       resources:
         requests:
           cpu: "1"
           memory: 300Mi
       terminationMessagePath: /dev/termination-log
       terminationMessagePolicy: File
     terminationGracePeriodSeconds: 30