apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: internal-psi-monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/oyegokeodev/oye-gitops.git'
    targetRevision: HEAD
    path: internal-psi-monitoring/applications
    directory:
      recurse: true # Ensures all apps in the directory are managed
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd # You can set this to "" or a management namespace if preferred
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
